name: CI Workflow
on:
  push:
    branches:
      - 'main'
    paths:
      - 'back-end/**'
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Test
        working-directory: back-end/
        run: mvn --activate-profiles prod test
  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Compilação / Package
        working-directory: back-end/
        run: mvn --activate-profiles prod -DskipTests package
